.TH BASEX 1 2020-08-02

.SH NAME
baseX \- convert from one base from another

.SH SYNOPSIS
.B baseX
[\fB\-\-help]
[\fB\-\-version]
[\fB\-s]
[\fB\-h\fR \fIhex\fR]
[\fB\-d\fR \fIdecimal\fR]
[\fB\-b\fR \fIbinary\fR]
[\fB\-o\fR \fIoctal\fR]

.SH DESCRIPTION
.B baseX
converts from one base to another base

.SH OPTIONS
\" indent next line
.TP
.BR \-h ", " \-\-help
displays this help information.

.TP
.BR \-v ", " \-\-version
displays version information.

.TP
.BR \-s
indicates that input value is sign

.TP
.BR \-d
input value is decimal

.TP
.BR \-b
input value is binary

.TP
.BR \-h
input value is hex

.TP
.BR \-o
input value is octal


.SH FILES
.TP
.I /bin/baseX

.SH AUTHOR
Vithurshan <vithurshan@laposte.net>
